name: SendGrid Smoke Test
on: { workflow_dispatch: {} }

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send a test email
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}   # your verified Single Sender
          EMAIL_TO: ${{ secrets.EMAIL_TO }}       # optional; defaults to EMAIL_FROM
        run: |
          set -euo pipefail

          : "${SENDGRID_API_KEY:?Missing SENDGRID_API_KEY}"
          : "${EMAIL_FROM:?Missing EMAIL_FROM}"

          TO="${EMAIL_TO:-$EMAIL_FROM}"

          BODY="{\"personalizations\":[{\"to\":[{\"email\":\"$TO\"}]}],\"from\":{\"email\":\"$EMAIL_FROM\"},\"subject\":\"TideFly test\",\"content\":[{\"type\":\"text/plain\",\"value\":\"Hello from TideFly!\"}]}"

          curl -sS -D /tmp/h -o /tmp/b https://api.sendgrid.com/v3/mail/send \
            -H "Authorization: Bearer $SENDGRID_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$BODY" || true

          echo "=== STATUS ==="; head -1 /tmp/h || true
          echo "=== HEADERS ==="; sed -n '1,20p' /tmp/h || true
          echo "=== BODY ==="; cat /tmp/b || true

          grep -q "202 Accepted" /tmp/h
