name: Surf Flight Worker
on:
  schedule:
    - cron: "5 * * * *"   # hourly at :05 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
      AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}
      AMADEUS_ENV: test
      PYTHONUNBUFFERED: '1'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r worker/requirements.txt
      - name: Run worker (unbuffered)
        run: python -u worker/worker.py
