name: Worker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  worker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: worker/requirements.txt

      # Normalize secrets to remove accidental CR/LF
      - name: Normalize secrets (strip CR/LF)
        shell: bash
        run: |
          echo "SUPABASE_URL=$(printf %s \"$SUPABASE_URL\" | tr -d '\r\n')" >> $GITHUB_ENV
          echo "SUPABASE_SERVICE_KEY=$(printf %s \"$SUPABASE_SERVICE_KEY\" | tr -d '\r\n')" >> $GITHUB_ENV
          echo "RESEND_API_KEY=$(printf %s \"$RESEND_API_KEY\" | tr -d '\r\n')" >> $GITHUB_ENV

      # Fail fast if a critical secret is missing
      - name: Sanity check required secrets
        shell: bash
        run: |
          test -n "$SUPABASE_URL" || { echo "SUPABASE_URL missing"; exit 1; }
          test -n "$SUPABASE_SERVICE_KEY" || { echo "SUPABASE_SERVICE_KEY missing"; exit 1; }

      - run: python -m pip install --upgrade pip
      - run: pip install -r worker/requirements.txt

      - name: Run worker (unbuffered)
        run: python -u -m worker.core_worker

