name: Surf Flight Worker

on:
  schedule:
    - cron: "5 * * * *"  # hourly at :05 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    concurrency:
      group: surf-flight-worker-${{ github.ref }}
      cancel-in-progress: true

    timeout-minutes: 20

    permissions:
      contents: read

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      ENABLE_AFFILIATES: ${{ secrets.ENABLE_AFFILIATES }}
      AVIA_AFFILIATE_ID: ${{ secrets.AVIA_AFFILIATE_ID }}
      ENABLE_HOTEL_CTA: ${{ secrets.ENABLE_HOTEL_CTA }}
      TP_P_HOTELLOOK: ${{ secrets.TP_P_HOTELLOOK }}
      AMADEUS_ENV: ${{ secrets.AMADEUS_ENV }}
      AMADEUS_MODE: ${{ secrets.AMADEUS_MODE }}
      AMADEUS_FAKE_PRICE: ${{ secrets.AMADEUS_FAKE_PRICE }}
      AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
      AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}
      ENABLE_FORECAST_CHECK: ${{ secrets.ENABLE_FORECAST_CHECK }}
      DRY_RUN: ${{ secrets.DRY_RUN }}
      PYTHONUNBUFFERED: '1'
      PIP_DISABLE_PIP_VERSION_CHECK: '1'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: worker/requirements.txt

      - run: python -m pip install --upgrade pip
      - run: pip install -r worker/requirements.txt

      - name: Validate required env vars (no values printed)
        run: |
          set -e
          missing=()
          req=(SUPABASE_URL SUPABASE_SERVICE_KEY EMAIL_FROM)
          if [ "${DRY_RUN}" != "true" ]; then
            req+=(RESEND_API_KEY)
          fi
          for v in "${req[@]}"; do
            if [ -z "${!v}" ]; then
              missing+=("$v")
            fi
          done
          if [ ${#missing[@]} -gt 0 ]; then
            echo "❌ Missing required env vars: ${missing[*]}"
            exit 1
          fi
          echo "✅ Env check passed"

      - name: Safety: auto-enable DRY_RUN if no RESEND_API_KEY
        run: |
          if [ -z "${RESEND_API_KEY}" ]; then
            echo "RESEND_API_KEY is empty; forcing DRY_RUN=true to prevent real sends"
            echo "DRY_RUN=true" >> $GITHUB_ENV
          fi

      - name: Run worker (unbuffered)
        run: python -u -m worker.core_worker

