name: Worker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  worker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Normalize secrets (strip CR/LF)
      shell: bash
      run: |
        for k in SUPABASE_URL SUPABASE_SERVICE_KEY RESEND_API_KEY; do
          v=$(printf %s "${!k}" | tr -d '\r\n')
          echo "$k=$v" >> "$GITHUB_ENV"
        done
    
    - name: Sanity check required secrets (safe)
      shell: bash
      run: |
        [[ "${SUPABASE_URL}" == https://* ]] || { echo "SUPABASE_URL not https://"; exit 1; }
        [[ "${SUPABASE_URL}" == *supabase.* ]] || { echo "SUPABASE_URL not a supabase domain"; exit 1; }
        [[ -n "${SUPABASE_SERVICE_KEY}" ]] || { echo "SUPABASE_SERVICE_KEY empty"; exit 1; }
        echo "SUPABASE_URL length: ${#SUPABASE_URL}"
        echo "SERVICE_KEY length: ${#SUPABASE_SERVICE_KEY}"
    
    - run: python -m pip install --upgrade pip
    
    - run: pip install -r worker/requirements.txt
    
    - name: Run worker (unbuffered)
      run: python -u -m worker.core_worker
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}